# Change these first
owner: Happy-Vibes-Bot # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Happy Vibes Bot 1
    url: $BOT1
    expectedStatusCodes:
      - 200
  - name: Happy Vibes Bot 2
    url: $BOT2
    expectedStatusCodes:
      - 200
  - name: Happy Vibes Bot 3
    url: $BOT3
    expectedStatusCodes:
      - 200
  - name: Happy Vibes Bot 4
    url: $BOT4
    expectedStatusCodes:
      - 200
  - name: Happy Vibes Bot 5
    url: $BOT5
    expectedStatusCodes:
      - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/88794125?s=88&v=4
  name: Happy Vibes Bot Status
  introTitle: "**Welcome!**"
  introMessage: Here, you may see the status of the Discord Happy Vibes Bot.
    - title: Home
      href: https://sites.google.com/view/happy-vibes-discord-bot/home

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
